Vagrant.configure("2") do |config|
  # VM Configuration
  config.vm.box = "almalinux/8"
  config.vm.hostname = "almalinux-dev-nova"
  config.vm.boot_timeout = 900  # Set to 900 seconds or higher

  # Network Configuration
  config.vm.network "forwarded_port", 
    guest: 80, 
    host: 8080, 
    host_ip: "127.0.0.1",
    auto_correct: true

  # Resource Configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.name = "almalinux-dev-nova"
  end

  # Provisioning
  config.vm.provision "shell", 
    path: "provision.sh",
    privileged: true

  config.vm.synced_folder "C:/Users/danni/iCloudDrive/projetos/devops-mao-na-massa/vagrant-lab/html", "/vagrant/html"


end
